services:
  - type: web
    name: feedplan
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn appred.wsgi:application
    disk:
      name: feedplan-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: appred.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: DATABASE_PATH
        value: /var/data/db.sqlite3
      - key: MEDIA_ROOT
        value: /var/data/media
