# Generated by Django 6.0.6 on 2026-06-26 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="feeds/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("IMG", "Imagen"),
                            ("CAR", "Carrusel"),
                            ("REL", "Reel"),
                        ],
                        default="IMG",
                        max_length=3,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("LU", "Lunes"),
                            ("MA", "Martes"),
                            ("MI", "Miercoles"),
                            ("JU", "Jueves"),
                            ("VI", "Viernes"),
                            ("SA", "Sabado"),
                            ("DO", "Domingo"),
                        ],
                        max_length=2,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("images", models.ManyToManyField(blank=True, to="planner.mediapost")),
            ],
            options={
                "ordering": ["day", "time", "-created_at"],
            },
        ),
    ]
